### PR TITLE
Updated to Rollup v0.67.0

### PR DESCRIPTION
**Pull request by hash-bang**

### CODE REVIEW

**Comment by hash-bang** [comment]
See attached PR for update to latest Rollup.
Package will need version bumping and republishing if you're happy.

**Comment by hash-bang** [comment]
Sorry, not quite following here. Do you mean just correct that line?

Is there some issue related to this or is this something to keep compatibility with other modules?

**Comment by tivac** [comment]
`ongenerate` is deprecated, so I was hoping that you could update it while you're in the file already.

**Comment by tivac** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
